// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: PollUserRequest.proto

package standards

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PollUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Verification   *Verification `protobuf:"bytes,1,opt,name=verification,proto3" json:"verification,omitempty"`
	LastseentaskID uint32        `protobuf:"varint,2,opt,name=lastseentaskID,proto3" json:"lastseentaskID,omitempty"`
}

func (x *PollUserRequest) Reset() {
	*x = PollUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PollUserRequest_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PollUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollUserRequest) ProtoMessage() {}

func (x *PollUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PollUserRequest_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollUserRequest.ProtoReflect.Descriptor instead.
func (*PollUserRequest) Descriptor() ([]byte, []int) {
	return file_PollUserRequest_proto_rawDescGZIP(), []int{0}
}

func (x *PollUserRequest) GetVerification() *Verification {
	if x != nil {
		return x.Verification
	}
	return nil
}

func (x *PollUserRequest) GetLastseentaskID() uint32 {
	if x != nil {
		return x.LastseentaskID
	}
	return 0
}

var File_PollUserRequest_proto protoreflect.FileDescriptor

var file_PollUserRequest_proto_rawDesc = []byte{
	0x0a, 0x15, 0x50, 0x6f, 0x6c, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x74, 0x61, 0x73, 0x6b, 0x6d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x2e, 0x70, 0x62, 0x1a, 0x12, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7b, 0x0a, 0x0f, 0x50,
	0x6f, 0x6c, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x40,
	0x0a, 0x0c, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x6d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x72, 0x2e, 0x70, 0x62, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x0c, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x26, 0x0a, 0x0e, 0x6c, 0x61, 0x73, 0x74, 0x73, 0x65, 0x65, 0x6e, 0x74, 0x61, 0x73, 0x6b,
	0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x6c, 0x61, 0x73, 0x74, 0x73, 0x65,
	0x65, 0x6e, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x44, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x69, 0x61, 0x72, 0x6d, 0x75, 0x69, 0x64, 0x6d,
	0x61, 0x6c, 0x61, 0x6e, 0x61, 0x70, 0x68, 0x79, 0x2f, 0x54, 0x61, 0x73, 0x6b, 0x2d, 0x4d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_PollUserRequest_proto_rawDescOnce sync.Once
	file_PollUserRequest_proto_rawDescData = file_PollUserRequest_proto_rawDesc
)

func file_PollUserRequest_proto_rawDescGZIP() []byte {
	file_PollUserRequest_proto_rawDescOnce.Do(func() {
		file_PollUserRequest_proto_rawDescData = protoimpl.X.CompressGZIP(file_PollUserRequest_proto_rawDescData)
	})
	return file_PollUserRequest_proto_rawDescData
}

var file_PollUserRequest_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_PollUserRequest_proto_goTypes = []any{
	(*PollUserRequest)(nil), // 0: taskmanager.pb.PollUserRequest
	(*Verification)(nil),    // 1: taskmanager.pb.Verification
}
var file_PollUserRequest_proto_depIdxs = []int32{
	1, // 0: taskmanager.pb.PollUserRequest.verification:type_name -> taskmanager.pb.Verification
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_PollUserRequest_proto_init() }
func file_PollUserRequest_proto_init() {
	if File_PollUserRequest_proto != nil {
		return
	}
	file_Verification_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_PollUserRequest_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*PollUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_PollUserRequest_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PollUserRequest_proto_goTypes,
		DependencyIndexes: file_PollUserRequest_proto_depIdxs,
		MessageInfos:      file_PollUserRequest_proto_msgTypes,
	}.Build()
	File_PollUserRequest_proto = out.File
	file_PollUserRequest_proto_rawDesc = nil
	file_PollUserRequest_proto_goTypes = nil
	file_PollUserRequest_proto_depIdxs = nil
}
