// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: Verification.proto

package proto_standards

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitialVerification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username *Username `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Hash     *Hash     `protobuf:"bytes,2,opt,name=Hash,proto3" json:"Hash,omitempty"`
}

func (x *InitialVerification) Reset() {
	*x = InitialVerification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Verification_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitialVerification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitialVerification) ProtoMessage() {}

func (x *InitialVerification) ProtoReflect() protoreflect.Message {
	mi := &file_Verification_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitialVerification.ProtoReflect.Descriptor instead.
func (*InitialVerification) Descriptor() ([]byte, []int) {
	return file_Verification_proto_rawDescGZIP(), []int{0}
}

func (x *InitialVerification) GetUsername() *Username {
	if x != nil {
		return x.Username
	}
	return nil
}

func (x *InitialVerification) GetHash() *Hash {
	if x != nil {
		return x.Hash
	}
	return nil
}

type VerificationToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token   []byte `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // Hex-encoded string of the 32-byte token
	UserID  uint64 `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
	Expires uint64 `protobuf:"varint,3,opt,name=expires,proto3" json:"expires,omitempty"`
}

func (x *VerificationToken) Reset() {
	*x = VerificationToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Verification_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerificationToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationToken) ProtoMessage() {}

func (x *VerificationToken) ProtoReflect() protoreflect.Message {
	mi := &file_Verification_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationToken.ProtoReflect.Descriptor instead.
func (*VerificationToken) Descriptor() ([]byte, []int) {
	return file_Verification_proto_rawDescGZIP(), []int{1}
}

func (x *VerificationToken) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *VerificationToken) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *VerificationToken) GetExpires() uint64 {
	if x != nil {
		return x.Expires
	}
	return 0
}

var File_Verification_proto protoreflect.FileDescriptor

var file_Verification_proto_rawDesc = []byte{
	0x0a, 0x12, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x74, 0x61, 0x73, 0x6b, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x72, 0x2e, 0x70, 0x62, 0x1a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x48, 0x61, 0x73, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x75, 0x0a, 0x13, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x34, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x74, 0x61, 0x73, 0x6b,
	0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a,
	0x04, 0x48, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x74, 0x61,
	0x73, 0x6b, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x61, 0x73,
	0x68, 0x52, 0x04, 0x48, 0x61, 0x73, 0x68, 0x22, 0x5b, 0x0a, 0x11, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x78,
	0x70, 0x69, 0x72, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x65, 0x78, 0x70,
	0x69, 0x72, 0x65, 0x73, 0x42, 0x42, 0x5a, 0x40, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x44, 0x69, 0x61, 0x72, 0x6d, 0x75, 0x69, 0x64, 0x4d, 0x61, 0x6c, 0x61, 0x6e,
	0x61, 0x70, 0x68, 0x79, 0x2f, 0x54, 0x61, 0x73, 0x6b, 0x2d, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x72, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x73,
	0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Verification_proto_rawDescOnce sync.Once
	file_Verification_proto_rawDescData = file_Verification_proto_rawDesc
)

func file_Verification_proto_rawDescGZIP() []byte {
	file_Verification_proto_rawDescOnce.Do(func() {
		file_Verification_proto_rawDescData = protoimpl.X.CompressGZIP(file_Verification_proto_rawDescData)
	})
	return file_Verification_proto_rawDescData
}

var file_Verification_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_Verification_proto_goTypes = []any{
	(*InitialVerification)(nil), // 0: taskmanager.pb.InitialVerification
	(*VerificationToken)(nil),   // 1: taskmanager.pb.VerificationToken
	(*Username)(nil),            // 2: taskmanager.pb.Username
	(*Hash)(nil),                // 3: taskmanager.pb.Hash
}
var file_Verification_proto_depIdxs = []int32{
	2, // 0: taskmanager.pb.InitialVerification.Username:type_name -> taskmanager.pb.Username
	3, // 1: taskmanager.pb.InitialVerification.Hash:type_name -> taskmanager.pb.Hash
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_Verification_proto_init() }
func file_Verification_proto_init() {
	if File_Verification_proto != nil {
		return
	}
	file_Username_proto_init()
	file_Hash_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_Verification_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*InitialVerification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Verification_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*VerificationToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Verification_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Verification_proto_goTypes,
		DependencyIndexes: file_Verification_proto_depIdxs,
		MessageInfos:      file_Verification_proto_msgTypes,
	}.Build()
	File_Verification_proto = out.File
	file_Verification_proto_rawDesc = nil
	file_Verification_proto_goTypes = nil
	file_Verification_proto_depIdxs = nil
}
